In [ ]:
import pandas as pd
s = pd.Series(["Matematicas", "Historia","Economia","Programacion","Ingles"], dtype = "string")
print(s)

0     Matematicas
1        Historia
2        Economia
3    Programacion
4          Ingles
dtype: string

In [ ]:
import pandas as pd
s = pd.Series({"Matematicas": 6.0,"Economia": 4.5,"Programacion": 8.5})
print(s)

Matematicas     6.0
Economia        4.5
Programacion    8.5
dtype: float64

In [ ]:
s = pd.Series([1,2,2,3,3,3,4,4,4,4])
s.size

s.index

s.dtype

dtype('int64')

In [ ]:
s[1:3]

Economia        4.5
Programacion    8.5
dtype: float64

In [ ]:
s[["Economia"]]

Economia    4.5
dtype: float64

In [ ]:
s[["Programacion","Matematicas"]]

Programacion    8.5
Matematicas     6.0
dtype: float64

In [ ]:
s = pd.Series([1,1,1,1,2,2,2,3,3,4])
s.count()
s.sum()
s.cumsum()
s.value_counts()
s.value_counts(normalize=True)
s.min()
s.max()
s.mean()
s.std()
s.describe()

count    10.000000
mean      2.000000
std       1.054093
min       1.000000
25%       1.000000
50%       2.000000
75%       2.750000
max       4.000000
dtype: float64

In [ ]:
s = pd.Series([1,2,3,4])
s*2

0    2
1    4
2    6
3    8
dtype: int64

In [ ]:
s%2

0    1
1    0
2    1
3    0
dtype: int64

In [ ]:
s = pd.Series(["a","b","c"])
s*5

0    aaaaa
1    bbbbb
2    ccccc
dtype: object

In [ ]:
from math import log
s = pd.Series([1,2,3,4])
s.apply(log)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
dtype: float64

In [ ]:
s = pd.Series (["a", "b", "c"])
s.apply(str.upper)

0    A
1    B
2    C
dtype: object

In [ ]:
s = pd.Series({"Matematicas": 6.0,"Economia": 4.5,"Programacion": 8.5})
print(s[s>5])

Matematicas     6.0
Programacion    8.5
dtype: float64

In [ ]:
s = pd.Series({"Matematicas": 6.0,"Economia": 4.5,"Programacion": 8.5})
print(s.sort_values())
print(s.sort_index(ascending = False))

Economia        4.5
Matematicas     6.0
Programacion    8.5
dtype: float64
Programacion    8.5
Matematicas     6.0
Economia        4.5
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series(["a","b",None,"c",np.nan,"d"])
s
s.dropna()

0    a
1    b
3    c
5    d
dtype: object

In [ ]:
datos = {"nombre":["Maria","Luis","Carmen","Antonio"],"edad":[18,22,20,21],"grado":["Economia","medicina","Arquitectura","Economia"],"correo":["maria@gmail.com","luis.yahoo.es","carmen@gmail.com","antonio@gmail.com"]}
df = pd.DataFrame(datos)

df

    nombre  edad         grado             correo
0    Maria    18      Economia    maria@gmail.com
1     Luis    22      medicina      luis.yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economia  antonio@gmail.com

In [ ]:
df = pd.DataFrame([["Maria",18],["Luis",22],["Carmen",20]],columns = ["Nombre","Edad"])
print(df)

   Nombre  Edad
0   Maria    18
1    Luis    22
2  Carmen    20

In [ ]:
df = pd.DataFrame([{"Nombre":"Maria","Edad":18},{"Nombre":"Luis","Edad":22},{"Nombre":"Carmen"}])
print(df)

   Nombre  Edad
0   Maria  18.0
1    Luis  22.0
2  Carmen   NaN

In [ ]:
df = pd.DataFrame(np.random.randn(4,3),columns = ["a","b","c"])
print(df)

          a         b         c
0 -0.556559 -0.161784 -2.051126
1  1.184905 -0.373371 -1.920504
2  0.775594 -0.559013 -1.156171
3 -0.606969 -0.378659  0.135475

In [9]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv", sep=";", decimal=",")
df

                             nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv")

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv")
print(df.rename(columns={"nombre":"nombre y apellidos", "altura":"estatura"}, index={0:1000,1:1001,2:1002}))

                                           nombre;edad;sexo;peso;altura;colesterol
José Luis Martínez Izquierdo;18;H;85;1                                      79;182
Rosa Díaz Díaz;32;M;65;1                                                    73;232
Javier García Sánchez;24;H;;1                                               81;191
Carmen López Pinzón;35;M;65;1                                               70;200
Marisa López Collado;46;M;51;1                                              58;148
Antonio Ruiz Cruz;68;H;66;1                                                 74;249
Antonio Fernández Ocaña;51;H;62;1                                           72;276
Pilar Martín González;22;M;60;1                                                66;
Pedro Gálvez Tenorio;35;H;90;1                                              94;241
Santiago Reillo Manzano;46;H;75;1                                           85;280
Macarena Álvarez Luna;53;M;55;1                                             62;262
José María de la Guía Sanz;58;H;78;1                                        87;198
Miguel Angel Cuadrado Gutiérrez;27;H;109;1                                  98;210
Carolina Rubio Moreno;20;M;61;1                                             77;194

In [ ]:
df.reindex(index=[4,3,1], columns=['nombre','tensión','colesterol'])

  nombre tensión colesterol
4    NaN     NaN        NaN
3    NaN     NaN        NaN
1    NaN     NaN        NaN

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv")
print(df.iloc[1,3])

IndexError: index 3 is out of bounds for axis 0 with size 1

In [ ]:
print(df.iloc[1,:2])

nombre;edad;sexo;peso;altura;colesterol    73;232
Name: Rosa Díaz Díaz;32;M;65;1, dtype: object

In [ ]:
print(df["colesterol"])

KeyError: 'colesterol'

In [ ]:
df["diabetes"] = pd.series([False,False,True,False,True])
print(df)

AttributeError: module 'pandas' has no attribute 'series'

In [ ]:
print(df["altura"] * 100)

KeyError: 'altura'

In [ ]:
print(df["altura"].apply(log))

KeyError: 'altura'

In [ ]:
df = pd.DataFrame({"Name": ["Maria", "Carlos", "Carmen"], "Nacimiento":["05-03-2000","20-05-"]})

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv")
df.describe()

       nombre;edad;sexo;peso;altura;colesterol
count                                       14
unique                                      14
top                                     79;182
freq                                         1

In [ ]:
df.describe(include="object")

       nombre;edad;sexo;peso;altura;colesterol
count                                       14
unique                                      14
top                                     79;182
freq                                         1

In [10]:
edad = df.pop("edad")
print(df)

                             nombre sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    M   65.0    1.73       232.0
2             Javier García Sánchez    H    NaN    1.81       191.0
3               Carmen López Pinzón    M   65.0    1.70       200.0
4              Marisa López Collado    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    H   62.0    1.72       276.0
7             Pilar Martín González    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    M   55.0    1.62       262.0
11       José María de la Guía Sanz    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    M   61.0    1.77       194.0

In [12]:
df = df.concat(pd.Series(["Carlos Rivas", 28, "H",89.0,1.78,245.0], index = ["nombre","edad","sexo","peso","altura","colesterol"]),ignore_index = True)
print(df.tail())

AttributeError: 'DataFrame' object has no attribute 'concat'

In [13]:
print(df.drop([1,3]))

                             nombre sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    H   85.0    1.79       182.0
2             Javier García Sánchez    H    NaN    1.81       191.0
4              Marisa López Collado    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    H   62.0    1.72       276.0
7             Pilar Martín González    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    M   55.0    1.62       262.0
11       José María de la Guía Sanz    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    M   61.0    1.77       194.0

In [14]:
print(df[(df["sexo"] == "H") & (df["colesterol"] > 260)])

                    nombre sexo  peso  altura  colesterol
6  Antonio Fernández Ocaña    H  62.0    1.72       276.0
9  Santiago Reillo Manzano    H  75.0    1.85       280.0

In [15]:
print(df.sort_values("colesterol"))

                             nombre sexo   peso  altura  colesterol
4              Marisa López Collado    M   51.0    1.58       148.0
0      José Luis Martínez Izquierdo    H   85.0    1.79       182.0
2             Javier García Sánchez    H    NaN    1.81       191.0
13            Carolina Rubio Moreno    M   61.0    1.77       194.0
11       José María de la Guía Sanz    H   78.0    1.87       198.0
3               Carmen López Pinzón    M   65.0    1.70       200.0
12  Miguel Angel Cuadrado Gutiérrez    H  109.0    1.98       210.0
1                    Rosa Díaz Díaz    M   65.0    1.73       232.0
8              Pedro Gálvez Tenorio    H   90.0    1.94       241.0
5                 Antonio Ruiz Cruz    H   66.0    1.74       249.0
10            Macarena Álvarez Luna    M   55.0    1.62       262.0
6           Antonio Fernández Ocaña    H   62.0    1.72       276.0
9           Santiago Reillo Manzano    H   75.0    1.85       280.0
7             Pilar Martín González    M   60.0    1.66         NaN

In [16]:
print(df.dropna())

                             nombre sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    M   65.0    1.73       232.0
3               Carmen López Pinzón    M   65.0    1.70       200.0
4              Marisa López Collado    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    H   62.0    1.72       276.0
8              Pedro Gálvez Tenorio    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    M   55.0    1.62       262.0
11       José María de la Guía Sanz    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    M   61.0    1.77       194.0

In [17]:
print(df.groupby("sexo").groups)

{'H': [0, 2, 5, 6, 8, 9, 11, 12], 'M': [1, 3, 4, 7, 10, 13]}

In [18]:
print(df.groupby(["sexo","edad"]).groups)

KeyError: 'edad'

In [19]:
print(df.groupby("sexo").get.group("M"))

AttributeError: 'DataFrameGroupBy' object has no attribute 'get'

In [22]:
print(df.groupby("sexo").agg(np.mean))

NameError: name 'np' is not defined

In [23]:
datos = {"nombre":["Maria","Luis","Carmen"],"edad":[18,22,20],"Matematicas":[8.5,7,3.5],"Economia":[8,6.5,5],"Programacion":[6.5,4,9]}
df = pd.DataFrame(datos)
df1 = df.melt(id_vars=["nombre","edad"],var_name="asignatura", value_name="nota")
print(df1)

   nombre  edad    asignatura  nota
0   Maria    18   Matematicas   8.5
1    Luis    22   Matematicas   7.0
2  Carmen    20   Matematicas   3.5
3   Maria    18      Economia   8.0
4    Luis    22      Economia   6.5
5  Carmen    20      Economia   5.0
6   Maria    18  Programacion   6.5
7    Luis    22  Programacion   4.0
8  Carmen    20  Programacion   9.0

In [24]:
print(df1.pivot(index="nombre",columns="asignatura",values="nota"))

asignatura  Economia  Matematicas  Programacion
nombre
Carmen           5.0          3.5           9.0
Luis             6.5          7.0           4.0
Maria            8.0          8.5           6.5

In [25]:
notas = pd.Series([87,100,85,60,78])
print(type(notas))
print(notas,"\n")

igualesaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaa
aaaaaaaaaaaaaa

<class 'pandas.core.series.Series'>
0     87
1    100
2     85
3     60
4     78
dtype: int64

NameError: name 'igualesaaaaaaaaaaaaaa' is not defined

In [ ]:
print("notas :")
print(f"{notas}")

print("\nSumarizacion descriptiva:")
print(notas.describe())
print(notas.describe())

In [ ]:
notas panfilo blah blah blah

In [ ]:
print(f"La calificacion de Rutilio es {notas_asignadas_dict["Rutilio"]}")
print(f"La calificacion de Rutilio es {notas_asignadas_dict.Rutilio")

In [26]:
SERAPADORES = ("*" * 60) + "\n"

diccionario_notas = {"Programacion":[87,80,80,20,100],
                     "Base de datos":[71,100,70,100,100],
                     "Contabilidad":[99,57,57,100,100]}

notas_diccionario = pd.DataFrame(diccionario_notas)
print(notas_diccionario)
print(SERAPADORES)

   Programacion  Base de datos  Contabilidad
0            87             71            99
1            80            100            57
2            80             70            57
3            20            100           100
4           100            100           100
************************************************************

In [27]:
notas_diccionario.index = ["Crescencio","Domitila","Rutilio","Panfilo","Ludoviko"]
print(notas_diccionario)
print(SERAPADORES)

            Programacion  Base de datos  Contabilidad
Crescencio            87             71            99
Domitila              80            100            57
Rutilio               80             70            57
Panfilo               20            100           100
Ludoviko             100            100           100
************************************************************